server:
  port: 8083

spring:
  application:
    name: ms-notificaciones

  rabbitmq:
    host: 172.31.55.46
    port: 5672
    username: guest
    password: guest

sendgrid:
  api-key: ${SENDGRID_API_KEY:}
  from-email: ${SENDGRID_FROM_EMAIL:}
  from-name: ${SENDGRID_FROM_NAME:PymeTrack}
  enabled: ${SENDGRID_ENABLED:true}

logging:
  level:
    cl.pymetrack.msnotificaciones: DEBUG